apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  SECRET_KEY: {{ .Values.config.secretKey | quote }}
  DEBUG: {{ .Values.config.debug | quote }}
  ALLOWED_HOSTS: {{ .Values.config.allowedHosts | quote }}
  POSTGRES_HOST: {{ .Values.config.postgresHost | quote }}
  POSTGRES_PORT: {{ .Values.config.postgresPort | quote }}
  POSTGRES_NAME: {{ .Values.config.postgresName | quote }}
  POSTGRES_USER: {{ .Values.config.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.config.postgresPassword | quote }}