replicaCount: 2

image:
  repository: 940482416787.dkr.ecr.eu-north-1.amazonaws.com/dashuk-ecr-lesson5
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5 
  cpuUtilization:
    targetAverageUtilization: 70

config:
  secretKey: "django-insecure-fxzvk@#lfms2$508e)%_8ol$a2&u&xpwr1m9f^^qtr*&h2gzky"
  debug: "True"
  allowedHosts: "*"
  postgresHost: "localhost"
  postgresPort: "5432"
  postgresName: "postgres"
  postgresUser: "postgres"
  postgresPassword: ""
